### ISSUE TITLE
Ability to declare other request methods

### ISSUE THREAD

**Issue by perry-mitchell** [nelsongomes/ts-openapi#13]
Currently the readme states:

> You can declare:
> *  get requests
> *  post requests
> *  delete requests
> *  put methods

But this isn't suitable for many APIs that make use of other requests like `PATCH`, etc.. Any plans on adding support? Would you accept a PR?

EDIT: Open API 3.0 seems to support these:
> OpenAPI 3.0 supports get, post, put, patch, delete, head, options, and trace.

**Comment by nelsongomes** [comment]
Yes I will accept any PRs, just make sure to add the unit tests for it also.
OpenAPI 3.0 supports get, post, put, patch, delete, head, options, and
trace.

Perry Mitchell ***@***.***> escreveu no dia sexta, 2/07/2021
à(s) 10:54:

**Comment by nelsongomes** [comment]
Do the initial PR and will check everything and complement anything that may be missing.

**Comment by nelsongomes** [comment]
Hey Perry, thought on this, if you give me next week, I think I can do it, is it good for you?

**Comment by nelsongomes** [comment]
@perry-mitchell  ☝️

**Comment by perry-mitchell** [comment]
Sorry, I’m on leave at the moment. I can definitely look at this when I’m back if you don’t get to it first! But appreciate the response either way :)

Cheers

**Comment by nelsongomes** [comment]
Hey @perry-mitchell pushed v0.3.0 with support for patch, can you check if it's good?

**Comment by nelsongomes** [comment]
do you need any verbs?

**Comment by nelsongomes** [comment]
@perry-mitchell if it's good for you please close the ticket.

**Comment by perry-mitchell** [comment]
Thanks a lot for this @nelsongomes - Really sorry I didn't respond to you earlier. Your update works perfectly and I can declare PATCH methods now.

Cheers for the great library!
