### ISSUE TITLE
Enum in response schema

### ISSUE THREAD

**Issue by kjkeefe** [nelsongomes/ts-openapi#22]
Forgive my clumsy request as I am learning pretty much on all fronts!

I'd like to be able to express that one my schema properties of my response object is a string enumeration. Something like this:

<pre>_status: {
    type: "string", 
    enum: ["RUNNING", "COMPLETED", "QUEUED", "ERROR"],
}</pre>

I don't think this is possible in the current release of ts-openapi, but it looks like it would fit the openapi specs: https://spec.openapis.org/oas/v3.0.3#schema-object

It'd be awesome if there was a way to tag each enum item with a description, but adding it to the description field of the whole property will suffice.

**Comment by nelsongomes** [comment]
check string enums here:

https://github.com/nelsongomes/ts-openapi/blob/HEAD/documentation/STRING.md

Ken Keefe ***@***.***> escreveu no dia quinta, 19/05/2022
à(s) 19:40:
