### ISSUE TITLE
ES6 Maps and Sets

### ISSUE THREAD

**Issue by kjkeefe** [nelsongomes/ts-openapi#24]
Feature request for Types.Map and Types.Set be added to describe the ES6 collections.

**Comment by nelsongomes** [comment]
Can you elaborate?

**Comment by kjkeefe** [comment]
I am suggesting adding the Map and Set types. For completeness, WeakMap, WeakSet, and Tuples should probably be added as well. https://techformist.com/typing-collections-typescript/

**Comment by nelsongomes** [comment]
And how does that map into OpenAPI spec?
