### ISSUE TITLE
Array of arrays not implemented

### ISSUE THREAD

**Issue by kjkeefe** [nelsongomes/ts-openapi#25]
When trying to describe the schema of an ES6 Map, I discovered that arrays of arrays are not yet implemented. Here is a sample:

<pre>_specs: Types.Object({
            properties: {
                dataType: Types.String({
                    description: "Must be \"Map\".",
                }),
                value: Types.Array({
                    description: "Array of key/value pairs.",
                    arrayType: Types.Array({
                        description: "Array of length two with the key in the 0th position and the value in the 1st.",
                        arrayType: Types.String()
                    }), 
                }),
            },
            description: "A map with names of agent specs as keys and the spec content as value."
        })
</pre>

**Comment by nelsongomes** [comment]
Deployed, thank you
