### ISSUE TITLE
Schema/models usage

### ISSUE THREAD

**Issue by Themis3000** [nelsongomes/ts-openapi#28]
I see that version 1.0 added support for schemas, but I'm sort of unsure on how to utilize them.

I've attempted to set a schema like this:

```js
const personSchema = Types.Object({
  properties: {
    id: Types.String(),
    name: Types.String()
  },
  description: "Person object"
})

openApi.checkAndSetSchema("person", personSchema)
```

I see the resulting json does show a person schema defined correctly. How do I reference this schema I just set under the key `person` now elsewhere? For now I've just been referencing the variable `personSchema` I defined for reuse, is that the correct way to go about utilizing a schema model?

I'm very new to openapi so let me know if there's something big I'm missing.

Thanks,

-Themis

**Comment by nelsongomes** [comment]
you just need to pass modelName: "ErrorResponse", just make sure all usages of the same model are equal.
