### ISSUE TITLE
Example parameter not being exported for responses

### ISSUE THREAD

**Issue by Themis3000** [nelsongomes/ts-openapi#29]
Hi,

I'm trying to set an example for a field, however it is not being exported into the final json document. It appears to export correctly for integer values, but not string values. It does however export an example string value correctly when it's within a param and not a response.

```js
const personSchema = Types.Object({
  properties: {
    id: Types.String({example: "example_id"}),  //Does not export example value into json
    authorization: Types.Integer({example: 2})  //Does export example value into json
  },
  description: "Person object"
})

openApi.addPath(
  "/person",
  {
    get: {
      description: "Get person",
      summary: "Gets a person from a group",
      operationId: "get-person",
      responses: {
        200: openApi.declareSchema("person", personSchema)
      },
      tags: ["People"]
    }
  },
true)
```

**Comment by nelsongomes** [comment]
Gives some days to look at it, please

**Comment by nelsongomes** [comment]
I have being working on this today, will publish a new release tomorrow

**Comment by nelsongomes** [comment]
w 1.1.4 you should be able to:

`const personSchema = Types.Object({
  properties: {
    id: Types.String(),  //Does not export example value into json
    authorization: Types.Integer()  //Does export example value into json
  },
  description: "Person object",
  example: { id: "customer1", authorization: 2 }
})`

because an example of the entire model, not of each property
