### ISSUE TITLE
Only one method per path

### ISSUE THREAD

**Issue by joaovq** [nelsongomes/ts-openapi#9]
Hey @nelsongomes, thank you for the pretty awsome package. It saves a lot of time when defining an open api. The only thing I didn't get is why it isnt possible to define more than one http method per path. Like, why can I have a post and put to the same endpoint?

Thank you

**Comment by nelsongomes** [comment]
Yes you can,

but the implementation only handles one declaration at the time. So you can
declare a post, and then declare a put.
But not both at the same time, in the same function call.

Maybe that is a thing that needs improvement.

Thanks,
Nelson Gomes

joaovq ***@***.***> escreveu no dia terça, 6/04/2021 à(s)
20:35:

**Comment by nelsongomes** [comment]
Hey,

I gave it a look and did a fix for it, I was not aware of this bug.
You can have it fixed on package v0.2.11

Give me any feedback you may find.

Thank you for your comment.

Nelson Gomes

joaovq ***@***.***> escreveu no dia terça, 6/04/2021 à(s)
20:35:

**Comment by joaovq** [comment]
@nelsongomes thank you so much for the fix. I will use it right now

**Comment by nelsongomes** [comment]
It is fixed, can I close this issue?
